export const INVENTORY_BRIDGE_PHASE_33_COUNTERPART_BASELINE_PHASE = "33.INVENTORY.A1";

export const INVENTORY_BRIDGE_PHASE_33_COUNTERPART_BASELINE_STATUS =
  "inventory-counterparts-confirmed-read-only";

export const INVENTORY_BRIDGE_PHASE_33_COUNTERPART_CONFIRMATION_STATUS =
  "inventory-counterparts-confirmed-no-activation";

export const INVENTORY_BRIDGE_PHASE_33_REQUIRED_COUNTERPART_COUNT = 8;

export const INVENTORY_BRIDGE_PHASE_33_ACTIVATION_STEPS_ALLOWED = 0;
